name: Build Electron App for macOS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Étape 4 : Vérifier les erreurs de configuration
      - name: Check Electron Builder config
        run: |
          if ! grep -q '"publish": "always"' package.json; then
            echo "Updating Electron Builder publish config..."
            sed -i '' 's/"publish":.*/"publish": "always",/' package.json
          fi
        shell: bash

      # Étape 5 : Construire l'application
      - name: Build Electron app
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # Étape 6 : Vérifier les fichiers générés
      - name: List artifacts
        run: ls -R dist
